# -*- coding: utf-8 -*-
"""A108260032-賴威宇-迴圈單元.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WO4FcVJhA7WWNiF_aQ4fiGNzAhqurFEk
"""

x=5
if x < 10:
  print("x is less than 10")

x=5 # 初始值
while x < 10: #判斷條件
  print("x is less than 10")
  print(" I am still here")
  x= x+1  #更新條件
print("Finished")

x=1 #初始值
while x < 5:  #判斷條件
  print("變數x是",x)
  x= x+1  #更新條件
print("Finished")

# 印10次HELLO

x=0 #初始值
while x < 10: #判斷條件
  x= x+1 #更新條件
  left = 10-x #更新條件
  print("This is",x,"times HELLO","You still have",left,"times.")
print("Finished")

#1到10之和

x=0 #初始值
sum=0 #初始值

while x < 10: #判斷條件
  x= x+1 #更新條件
  sum =sum+x #更新條件
  print("Sum is", sum)
print("Finished")

#1到10之和大於50

x=0 #初始值
sum=0 #初始值

while sum <= 10: #判斷條件
  x= x+1 #更新條件
  sum =sum+x #更新條件
  print("X is",x)
  print("Sum is", sum)
print("Finished")

#1到9奇數之和

sum =0  #初始值
x=1 #初始值

while x<11: #判斷條件
  sum=sum+x #更新條件
  x =x+2  #更新條件

print("1+3+5+7+9=",sum)  #最後結果

#求大於1000最小平方和的x

sum =0  #初始值
i =0  #初始值
while sum <=1000:
  i +=1
  sum +=i*i
print("最小的x為",i)

