# -*- coding: utf-8 -*-
"""A108260032賴威宇-重複迴圈.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N3zQFv4BWFYZqQPhlY0Bx0TfzA5DF2lH
"""

n=0 #初始條件
result=0
while n<10: #判斷條件
  n=n+1 #更新條件
  result=result+n #累加
print("Finished")

n=0 #初始條件

while n<10: #判斷條件
  n=n+1 #更新條件
  if n==4:
    break #跳離迴圈
print("Finished")

n=0 #初始條件

while n<10: #判斷條件
  n=n+1 #更新條件
  if n==4:
    continue #跳離迴圈+此次迴圈不執行
  print(n)
print("Finished")

#無窮迴圈:while True + break

while True:
  print("Hello")  #運算式
  if條件:
    執行動作
  else:
    break

#請寫一個程式模擬密碼登入，使用者輸入密碼，
#若密碼一致，則輸出「密碼正確」，否則輸出「登入失敗」，

while True:
  password=input("Enter Your Password:")
  if password =="answer":
    print("Correct")
    break
  else:
    print("Fail,Try Again")

#請寫一個程式模擬帳號與密碼登入，使用者輸入帳號與密碼，
#若帳號密碼一致，則輸出「帳號與密碼正確」，否則輸出「登入失敗」，

while True:
  account = input("請輸入帳號:")
  password = input("請輸入密碼:")
  if (account =="123" and password =="456"):
    print("帳號與密碼正確")
    break
  else:
    print("登入失敗")

#先設定好密碼 paswword，讓輸入者可以重複輸入密碼，「最多輸入3次」
#如果對的話,印出 "登入成功!"，如果不對,就印出"密碼錯誤!還有幾次機會"

password="wei666"
times = 0

while times<=3:
  answer=input("Enter Your Password:")
  if answer==password:
    print("登入成功!")
    break
  else:
    times=times+1
    chance=3-times
    print("密碼錯誤!還有",chance,"次機會")