# -*- coding: utf-8 -*-
"""Week3-A108260032-賴威宇.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rJLzACckbYmjl0w5jUYMz3mJVGckhW5z
"""

print("Hello World")